## Scraping settings

# List of boards to scrape (note: 3 must be written as "_3")
boards = [""]

# Seconds to wait between fetching the threads.json of each board
poll_interval = 30

# Milliseconds of delay between simultaneous requests
fetch_delay = 1_000


## Database/media settings
database_url = "mysql://username:password@localhost/ena"
charset = "utf8mb4"
media_dir = "media"


## Asagi/FoolFuuka compatibility

# Adjust timestamps to EST/EDT (should be `true` for compatibility)
adjust_timestamps = true

# On archived boards, fetch a thread again after archival. This allows for more accurate archive
# times (how much more depends on `poll_interval`) and catches sage posts/other updates which would
# otherwise have been missed, at the cost of an extra request (should be `true` for compatibility)
refetch_archived_threads = true

# Add archive times to bumped-off threads on boards that don't have archiving (should be `false`
# for compatibility)
always_add_archive_times = false

# Create the `index_counters` table used by Sphinx/FoolFuuka (should be `true` for compatibility)
create_index_counters = true