## Scraping settings

# List of boards to scrape (note: 3 must be written as "_3")
boards = [""]

# Seconds to wait between fetching the threads.json of each board
poll_interval = 30

# Milliseconds of delay between simultaneous requests
fetch_delay = 1_000

# In ambiguous situations, if a thread disappears, and was last seen on a page after this one, it is
# considered to have been bumped off. For example, if the threshold is 7, and a thread disappears
# from pages 1-7, it was deleted. Otherwise, it was bumped off.
# Note: This is a number from 0-10. 0 means that any removed thread was bumped off, and 10 means
# that any removed thread was deleted.
deleted_page_threshold = 7


## Database/media settings
database_url = "mysql://username:password@localhost/ena"
charset = "utf8mb4"
media_dir = "media"


## Asagi/FoolFuuka compatibility

# Adjust timestamps to EST/EDT (should be `true` for compatibility)
adjust_timestamps = true

# On archived boards, fetch a thread again after archival. This allows for more accurate archive
# times (how much more depends on `poll_interval`) and catches sage posts/other updates which would
# otherwise have been missed, at the cost of an extra request (should be `true` for compatibility)
refetch_archived_threads = true

# Add archive times to bumped-off threads on boards that don't have archiving (should be `false`
# for compatibility)
always_add_archive_times = false

# Create the `index_counters` table used by Sphinx/FoolFuuka (should be `true` for compatibility)
create_index_counters = true