## Scraping settings

# List of boards to scrape
boards = [""]

# Seconds to wait between fetching the threads.json of each board
poll_interval = 60

# On startup, fetch (and potentially update) threads from archive.json
fetch_archive = true

# Download full image/media files
download_media = true
# Download thumbnails
download_thumbs = true

# `interval` is in seconds.
# `max_interval` is the maximum number of requests that can be made in an interval.
# `max_concurrent` is the maximum number of requests that can run at once.

# Rate limiting for media and image files
media_rate_limiting = { interval = 60, max_interval = 600, max_concurrent = 150 }
# Rate limiting for individual threads
thread_rate_limiting = { interval = 60, max_interval = 200, max_concurrent = 75 }
# Rate limiting for threads.json and archive.json
thread_list_rate_limiting = { interval = 60, max_interval = 180, max_concurrent = 50 }


## Database/media settings
database_url = "mysql://username:password@localhost/ena"
charset = "utf8mb4"
media_dir = "media"


## Asagi/FoolFuuka compatibility

# Adjust timestamps to EST/EDT (should be `true` for compatibility)
adjust_timestamps = true

# On archived boards, fetch threads after they're bumped off. At the cost of an extra request, this
# allows for more accurate archive times (how much more depends on `poll_interval`) and catches sage
# posts/deletions/changes which would otherwise have been missed (should be `true` for compatibility)
refetch_archived_threads = true

# Add archive times to bumped-off threads on boards without archiving (should be `false` for
# compatibility)
always_add_archive_times = false

# Create the `index_counters` table used by Sphinx/FoolFuuka (should be `true` for compatibility)
create_index_counters = true