# Scraping settings
# List of boards to scrape (note: 3 must be written as "_3")
boards = [""]
# Seconds to wait between fetching the threads.json of each board
poll_interval = 30
# In ambiguous situations, if a thread disappears, and was last seen on a page after this one, it is
# considered to have been bumped off. For example, if the threshold is 7, and a thread disappears
# from pages 1-7, it was deleted. Otherwise, it was bumped off.
# Note: This is a number from 0-10. 0 means that any removed thread was bumped off, and 10 means
# that any removed thread was deleted.
deleted_page_threshold = 7


# Database settings
database_url = "mysql://username:password@localhost/ena"
charset = "utf8mb4"


# Asagi/FoolFuuka compatibility
# Adjust timestamps to EST/EDT (should be `true` for compatibility)
adjust_timestamps = true
